version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:TASK_DEFINITION_ARN:VERSION"
        LoadBalancerInfo:
          ContainerName: "fargate-app"
          ContainerPort: 8080